#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>

#include "program_arena.h"
#include "CMakeLists.h"
#include "source_files.h"
#include "configure_script.h"
#include "build_script.h"
#include "debug_script.h"
#include "run_script.h"
#include "CLI.h"

void validateProjectName (arena * program_arena)
{
  char bad_chars[] = {'/', '.', '@', '#', '|', '&', '$', '{', '}', '[', ']', '(', ')', '*', ' '};

  uint32_t num_bad_chars = sizeof(bad_chars);

  for (uint32_t i = 0; i < num_bad_chars; i++)
  {
    char * BCloc = strchr(program_arena->project_name, bad_chars[i]);
    if (BCloc)
    {
      printf("\
ERROR: \"%c\" is not a permitted character to use as part of a name for a project\n\
generated by this program. Characters not permitted to be used are:\n\n",
bad_chars[i]);

      for (uint32_t j = 0; j < num_bad_chars; j++)
      {
        printf("%c%c", 
               bad_chars[j], 
               (j == num_bad_chars - 1) ? '\n' : ' ');
      }

      freeArena(program_arena);
      exit(EXIT_FAILURE);
    }
  }
}


int main (int argc, char ** argv)
{
  arena * program_arena = parseCLI(argc, argv);

  validateProjectName(program_arena);

  //  CMakeLists.txt file run by configure script
  genCMakeListsFile(program_arena);

  //  generates main.c and config header file 
  genSourceFiles(program_arena);

  //  Scripts
  genConfigScript(program_arena);

  genBuildScript(program_arena);

  genDebugScript(program_arena);

  genRunScript(program_arena);

  freeArena(program_arena);

}

